version: "3"
services:
    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
        ports:
            - '9200:9200'
        environment:
            - xpack.security.enabled=false
            - discovery.type=single-node
        healthcheck:
            test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
            interval: 30s
            timeout: 30s
            retries: 3
